/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_network_NativeNetwork */

#ifndef _Included_crossplatformapi_jni_network_NativeNetwork
#define _Included_crossplatformapi_jni_network_NativeNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_network_NativeNetwork
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_crossplatformapi_jni_network_NativeNetwork_isConnected
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_network_NativeNetwork
 * Method:    getConnectedSSIDs
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_crossplatformapi_jni_network_NativeNetwork_getConnectedSSIDs
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_network_NativeNetwork
 * Method:    getAllSSIDs
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_crossplatformapi_jni_network_NativeNetwork_getAllSSIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
