/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_mouse_Mouse */

#ifndef _Included_crossplatformapi_jni_mouse_Mouse
#define _Included_crossplatformapi_jni_mouse_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_mouse_Mouse
 * Method:    press
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_Mouse_press
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_Mouse
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_Mouse_release
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_Mouse
 * Method:    click
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_Mouse_click
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_Mouse
 * Method:    move
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_Mouse_move
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
