/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_mouse_NativeMouseListener */

#ifndef _Included_crossplatformapi_jni_mouse_NativeMouseListener
#define _Included_crossplatformapi_jni_mouse_NativeMouseListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_mouse_NativeMouseListener
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouseListener_register
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouseListener
 * Method:    unregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouseListener_unregister
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouseListener
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouseListener_block
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouseListener
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouseListener_unblock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
