/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_keyboard_KeyboardListener */

#ifndef _Included_crossplatformapi_jni_keyboard_KeyboardListener
#define _Included_crossplatformapi_jni_keyboard_KeyboardListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_keyboard_KeyboardListener
 * Method:    registerListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_KeyboardListener_registerListener
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_KeyboardListener
 * Method:    unregisterListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_KeyboardListener_unregisterListener
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_KeyboardListener
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_KeyboardListener_block
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_KeyboardListener
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_KeyboardListener_unblock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
