/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_stats_PowerStates */

#ifndef _Included_crossplatformapi_jni_stats_PowerStates
#define _Included_crossplatformapi_jni_stats_PowerStates
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_stats_PowerStates
 * Method:    modernStandby
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_PowerStates_modernStandby
  (JNIEnv *, jobject);

/*
 * Class:     crossplatformapi_jni_stats_PowerStates
 * Method:    standby
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_PowerStates_standby
  (JNIEnv *, jobject);

/*
 * Class:     crossplatformapi_jni_stats_PowerStates
 * Method:    hibernate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_PowerStates_hibernate
  (JNIEnv *, jobject);

/*
 * Class:     crossplatformapi_jni_stats_PowerStates
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_PowerStates_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
