/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_keyboard_NativeKeyboardListener */

#ifndef _Included_crossplatformapi_jni_keyboard_NativeKeyboardListener
#define _Included_crossplatformapi_jni_keyboard_NativeKeyboardListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_keyboard_NativeKeyboardListener
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_NativeKeyboardListener_register
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_NativeKeyboardListener
 * Method:    unregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_NativeKeyboardListener_unregister
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_NativeKeyboardListener
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_NativeKeyboardListener_block
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_keyboard_NativeKeyboardListener
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_keyboard_NativeKeyboardListener_unblock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
