/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_battery_NativeBatteryListener */

#ifndef _Included_crossplatformapi_jni_battery_NativeBatteryListener
#define _Included_crossplatformapi_jni_battery_NativeBatteryListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_battery_NativeBatteryListener
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_battery_NativeBatteryListener_register
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_battery_NativeBatteryListener
 * Method:    unregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_battery_NativeBatteryListener_unregister
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
