/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_mouse_MouseListener */

#ifndef _Included_crossplatformapi_jni_mouse_MouseListener
#define _Included_crossplatformapi_jni_mouse_MouseListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_mouse_MouseListener
 * Method:    registerListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_MouseListener_registerListener
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_MouseListener
 * Method:    unregisterListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_MouseListener_unregisterListener
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_MouseListener
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_MouseListener_block
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_mouse_MouseListener
 * Method:    unblock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_MouseListener_unblock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
