/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_mouse_NativeMouse */

#ifndef _Included_crossplatformapi_jni_mouse_NativeMouse
#define _Included_crossplatformapi_jni_mouse_NativeMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    press
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_press
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_release
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    click
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_click
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    move
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_move
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    scroll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_scroll
  (JNIEnv *, jclass, jint);

/*
 * Class:     crossplatformapi_jni_mouse_NativeMouse
 * Method:    hscroll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_mouse_NativeMouse_hscroll
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
