/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_battery_NativeBattery */

#ifndef _Included_crossplatformapi_jni_battery_NativeBattery
#define _Included_crossplatformapi_jni_battery_NativeBattery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_battery_NativeBattery
 * Method:    getCapacityInPercent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_battery_NativeBattery_getCapacityInPercent
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_battery_NativeBattery
 * Method:    isPowerOnLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_crossplatformapi_jni_battery_NativeBattery_isPowerOnLine
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_battery_NativeBattery
 * Method:    isBatterySaverOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_crossplatformapi_jni_battery_NativeBattery_isBatterySaverOn
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_battery_NativeBattery
 * Method:    setBatterySaverOn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_battery_NativeBattery_setBatterySaverOn
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
