/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_users_User */

#ifndef _Included_crossplatformapi_jni_users_User
#define _Included_crossplatformapi_jni_users_User
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_users_User
 * Method:    lockScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_users_User_lockScreen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
