/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_debug_NativeDebug */

#ifndef _Included_crossplatformapi_jni_debug_NativeDebug
#define _Included_crossplatformapi_jni_debug_NativeDebug
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_debug_NativeDebug
 * Method:    printError
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_debug_NativeDebug_printError
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
