/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_stats_NativePowerStates */

#ifndef _Included_crossplatformapi_jni_stats_NativePowerStates
#define _Included_crossplatformapi_jni_stats_NativePowerStates
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    modernStandby
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_modernStandby
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    standby
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_standby
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    hibernate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_hibernate
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_reboot
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    logoff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_logoff
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_stats_NativePowerStates
 * Method:    lockScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_stats_NativePowerStates_lockScreen
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
