/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_battery_BatteryListener */

#ifndef _Included_crossplatformapi_jni_battery_BatteryListener
#define _Included_crossplatformapi_jni_battery_BatteryListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_battery_BatteryListener
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_battery_BatteryListener_register
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_battery_BatteryListener
 * Method:    unregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_battery_BatteryListener_unregister
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
