/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_display_NativeDisplay */

#ifndef _Included_crossplatformapi_jni_display_NativeDisplay
#define _Included_crossplatformapi_jni_display_NativeDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getMainDisplay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getMainDisplay
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getDisplays
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getDisplays
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getX
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getX
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getY
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getWidth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_display_NativeDisplay
 * Method:    getHeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crossplatformapi_jni_display_NativeDisplay_getHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
