/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_network_Network */

#ifndef _Included_crossplatformapi_jni_network_Network
#define _Included_crossplatformapi_jni_network_Network
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_network_Network
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_crossplatformapi_jni_network_Network_isConnected
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
