/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crossplatformapi_jni_window_WindowListener */

#ifndef _Included_crossplatformapi_jni_window_WindowListener
#define _Included_crossplatformapi_jni_window_WindowListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crossplatformapi_jni_window_WindowListener
 * Method:    registerListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_window_WindowListener_registerListener
  (JNIEnv *, jclass);

/*
 * Class:     crossplatformapi_jni_window_WindowListener
 * Method:    unregisterListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crossplatformapi_jni_window_WindowListener_unregisterListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
